spring:
  application:
    name: service--simulacao
  cache:
    type: redis
    redis:
      time-to-live: 60000 # TTL do cache em milissegundos (60 segundos)
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/simulacao-db
      database: simulacao-db

server:
  port: 8080
  servlet:
    context-path: /service--simulacao
  tomcat:
    threads:
      max: 200           # Máximo de threads simultâneas
      min-spare: 10      # Threads mínimas ociosas
    accept-count: 100     # Fila de requisições pendentes
    max-connections: 100 # Máximo de conexões TCP simultâneas 10000 default
    max-http-post-size: 1MB # Tamanho máximo do corpo POST 2MB default
  connection-timeout: 5s   # Tempo máximo de espera por requisição

logging:
  config: classpath:logback-spring.xml
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    br.com.creditas.service.simulacao.service: DEBUG
    org.zalando.logbook.Logbook: TRACE

# Configurações de negócio

juros:
  faixa-etaria:
    - idadeMin: 0
      idadeMax: 25
      taxa: 0.05
    - idadeMin: 26
      idadeMax: 40
      taxa: 0.03
    - idadeMin: 41
      idadeMax: 60
      taxa: 0.02
    - idadeMin: 61
      idadeMax: 99
      taxa: 0.04

logbook:
  format:
    style: json
  exclude:
    - /actuator/**
    - /health

